### PR TITLE
Don't use spaces in regexp

### LINKED ISSUE #2: doesn't match mention when first thing in a string
given: 

```js
@abc @foo xyz
```
returns

```
[ ' @foo ', 'foo', index: 4, input: '@abc @foo xyz' ]
```

should be `@abc`

### PR DESCRIPTION
**Pull request by blakeembrey**
Fixes #2

### CODE REVIEW

**Comment by blakeembrey** [comment]
FWIW, no tests added since there's nothing there right now. Haven't updated the readme either. Tests right now invalidly load mocha and should when they aren't needed. There's a typo on the readme too.

Since this changes the way matches occur, I didn't want to turn it into a conversion about the test implementation I use or anything else. But why isn't this tested or have CI?

**Comment by blakeembrey** [comment]
@tunnckoCore What's with the default max length too?

**Comment by tunnckoCore** [comment]
> Tests right now invalidly load mocha and should when they aren't needed.

Because the template that I use. 

> For a 1.0 library this is quite bad.

And yea, my fault. As you can see, last weeks I no longer publish v1 without tests and strictly review the readme and misc stuff, like links, typos and etc.

**Comment by tunnckoCore** [comment]
What for max length? It reasonable.

**Comment by jonschlinkert** [comment]
I don't think this is right. I know it fixes #2 but I think this regex in general needs a lot of work. 

> What for max length?

I think it should be hard-coded at the max length of twitter screen names. I can't remember what it is, I think 15 but not sure. consider making it longer if you get a request with a good use case. otherwise it's overhead.

**Comment by tunnckoCore** [comment]
@jonschlinkert 20, my is 21 and I remember it. Yea I work on. :)

**Comment by tunnckoCore** [comment]
Btw, it should have spaces.

**Comment by jonschlinkert** [comment]
yeah, it's 15. here it is: http://blog.justunfollow.com/2014/03/13/10-twitter-limits-any-smart-user-should-know/. 

> Btw, it should have spaces.

why? I've never seen `@` mentions allow spaces. that seems like a terrible delimiter. I don't think they should be allowed.

**Comment by tunnckoCore** [comment]
> why? I've never seen @ mentions allow spaces.

I mean, around the mention.

**Comment by tunnckoCore** [comment]
But my idea is to provide options to configure this needs.

**Comment by blakeembrey** [comment]
@tunnckoCore That's why I'm using `\b`

**Comment by blakeembrey** [comment]
> I don't think this is right. I know it fixes #2 but I think this regex in general needs a lot of work.

Agreed, and if that infrastructure existed I would. Since it doesn't, I stuck with the code that fixes the issue and the maintainer can fix the package properly, instead of changing everything with a giant commit containing unrelated fixes.

**Comment by tunnckoCore** [comment]
That isn't the solution. Yea, won't match emails, but will match things like `@tunn@ckoCore` which actually isn't proper mention. For this its necessary to use `\s` and optional configs for this.

```js
assert.strictEqual(regex().test('github @tunnckoCore'), true);
assert.strictEqual(regex().test('@tunnckoCore some'), true);
assert.strictEqual(regex().test('@tunnckoCore'), true);
assert.strictEqual(regex().test('@tunn@ckoCore'), true);
assert.strictEqual(regex().test('email@dot.com'), false);
```

**Comment by tunnckoCore** [comment]
Because of that I think its better to have options for `startSpace` and `endSpace`.

And then if you want to just `regex.test('@tunnckoCore')` , you should set `startSpace` and `endSpace` to false.

```js
var regex = /\s+@([a-z0-9_]{1,30})\s+/i;
assert.strictEqual(regex().test('github @tunnckoCore'), false);
assert.strictEqual(regex({endSpace: false}).test('@tunnckoCore some'), true);
assert.strictEqual(regex({startSpace: false, endSpace: false}).test('@tunnckoCore'), true);
assert.strictEqual(regex().test('@tunn@ckoCore'), false);
assert.strictEqual(regex().test('email@dot.com'), false);
```

**Comment by blakeembrey** [comment]
@tunnckoCore Did you actually run the test or look up what `\b` is? It works perfectly.

**Comment by tunnckoCore** [comment]
Yea, I did.

**Comment by jonschlinkert** [comment]
> I wouldn't expect to know whether it's surrounded by spaces or not, that's the point of this library.

agreed. I think this lib (and all of the regex libs) should provide consistent, reliable results. IMO, consistency and predictability are far more important and attractive to users than flexibility.

**Comment by tunnckoCore** [comment]
> I wouldn't expect to know whether it's surrounded by spaces or not

Yea, u have right guys. I think we should choose @jonschlinkert's solution, but with options. Are you okey with that, @blakeembrey ?

**Comment by jonschlinkert** [comment]
> but with options.

what options would there be? the only other options were whitespace (which should never be allowed in screen names) and length, which IMHO is a useless option. there should be a strict length limit or none at all. this is something the user shouldn't be asked to decide as there are already well-established conventions for screen names and parsing them. I think most implementors would find twitter's guidelines to be a reasonable model to follow.

the other thing is runtime compilation. _with options_ we have to pass a dynamically created string to the RegExp constructor, which is much slower than a regex literal. (I wish I could tell this to myself 18 mos ago). 

@tunnckoCore, I'm not trying to beat you over the head with my opinion, do what you think is best for what you need. I just think it's more likely to be used if it it's clear and specific 

just my 2c

**Comment by tunnckoCore** [comment]
Actually, I agree with you and understand you. But I think should have option for length, its reasonable to have. We should not force implementors to have some strict length.

But the case can be solved with single if `opts.length` then dynamically generate regex, else literal.

**Comment by jonschlinkert** [comment]
> But the case can be solved with single if opts.length then dynamically generate regex, else literal.

yeah, that's a good compromise.

**Comment by tunnckoCore** [comment]
Haha, okey.. This (your) solution is cool.
http://regexr.com/3acq0 `/(?!\b)@([0-9A-Za-z]{1,15})/`

```
abc @abc foo
@ abc@foo xyz
abc @ abc
abc some@email.de far
abc @dce
abc @goo.gl
abc @xyz!os
abc @qux*dex
abc @ubu^ntu
abc @foo!bar
abc @hash#tag
abc @musta{che
abc @@foobar   // should not match
abc @@pub@sub  // should not match
abc @#tag ok   // should match
abc@qux*dex
invalid @\\os
invalid @*inv
```
But we should think for these cases `@@foobar`, `@@pub@sub` and `@#tag` which differs from twitter's.

**Comment by tunnckoCore** [comment]
Ooookey, 100% twitter compatible, lol, but not github compatible.. And because the name of the package is `mentions-regex` I think we should provide some config options, its not `twitter-mention-regex`.

But yea, its a good thing to follow giants when you want to have same functionality :) And yea, its a good starting point to cover at least twitter cases :)

More use/edge cases @regexps/owners?

```js
var regexDot = /(?:^|[^a-zA-Z0-9_@＠])(@|＠)(?!\.)([a-zA-Z0-9_\.]{1,15})(?:\b(?!@)|$)/;
var regexNoDot = /(?:^|[^a-zA-Z0-9_@＠])(@|＠)([a-zA-Z0-9_]{1,15})(?:\b(?!@)|$)/;
```
**fixtures**
```
// should match `bar`, when opts.dot `bar.baz` 
foo @bar.baz qux

foo @bar_baz qux // should match `bar_baz`
foo @_bar // should match `_bar`
foo @2bar // should match `2bar`

// should match `google`, when opts.dot `google.com`
foo @google.com
foo .@bar

// should not match even opts.dot
foo @.bar
foo email@google.com
foo git@github.com:tunnckoCore/is-glob

// should not match
foo @bar@baz
foo @!bar
foo @@bar
foo @@bar@baz
foo @@bar!qux
foo @#bar

// should match only `bar`
foo @bar baz
foo @bar!baz qux
foo @bar#baz qux
foo @bar$baz qux
foo @bar%baz qux
foo @bar^baz qux
foo @bar&baz qux
foo @bar*baz qux
foo @bar(baz qux
foo @bar)baz qux
foo @bar{baz qux
foo @bar}baz qux
foo @bar<baz qux
foo @bar>baz qux
foo @bar[baz qux
foo @bar]baz qux
foo @bar=baz qux
foo @bar+baz qux
foo @bar-baz qux
foo @bar`baz qux
foo @bar/baz qux
foo @bar\baz qux
foo @bar:baz qux
foo @bar;baz qux
foo @bar?baz qux
foo @bar~baz qux
foo @bar|baz qux
foo @bar"baz qux
foo @bar'baz qux
```

**Comment by tunnckoCore** [comment]
@regexps/owners ping, thoughts?

**Comment by tunnckoCore** [comment]
@jonschlinkert ?

**Comment by jonschlinkert** [comment]
really have no idea, I personally would probably follow an established convention for it, like what I said in https://github.com/regexps/mentions-regex/pull/3#issuecomment-73537348

>  I think most implementors would find twitter's guidelines to be a reasonable model to follow.

**Comment by tunnckoCore** [comment]
>  would probably follow an established convention for it

latest regex (and examples) follow them.. as you said there 15 characters, no options nothing.
the question is are you okey with this matching, more use cases? I directly paste these on a tweet and it is 100% okey.

**Comment by tunnckoCore** [comment]
okey I've just update it more will commit up ASAP!

Thanks for the thoughts, discussion and ideas!

**Comment by jonschlinkert** [comment]
you're doing great. if you're good with it I'm good with it

**Comment by tunnckoCore** [comment]
damn ddos attacks...
Last 1 hour I playing with regex in twitter and finalize it totally :) its awesome now
http://regexr.com/3an0h , I dont like very much regexr.com because it highlights "the whole match" and more info and details and capturing groups are in the tooltip when hover the highlight.

**Comment by jonschlinkert** [comment]
> I dont like very much regexr.com

I like it quite a bit. I use it all the time. everyone has their own taste, maybe this will be better for you https://www.regex101.com/r/aD4oV1/1

**Comment by jonschlinkert** [comment]
nice work, looks great

**Comment by tunnckoCore** [comment]
> maybe this will be better for you

doh yea, I forgot it! :)

> nice work, looks great

thanks! 
but this ddos delay me. i forget what im doing ;d

**Comment by tunnckoCore** [comment]
yep, also npm is ddos-ed, damn

**Pull request closed without merging**
